#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isBalanced(s):
    st=[]
    for c in s:
        if c in '({[':st.append(c)
        elif c in ')}]': 
            if not st or (c==')' and st[-1]!='(') or (c=='}' and st[-1]!='{') or (c==']' and st[-1]!='['):return "NO"
            st.pop()
    return "YES" if not st else "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
